version: '3'
services:
  backend:
    build: .
    image: eval-backend
    ports:
      - "8080:8080"
    networks:
      evalnet:
        ipv4_address: 172.20.0.2
    env_file:
      - .env
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:4.0.4
    volumes:
      - ~/mongo/data:/data/db
    ports:
      - "27017-27019:27017-27019"
    networks:
      evalnet:
        ipv4_address: 172.20.0.3

networks:
  evalnet:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16